services:
  - name: offspring-backend
    type: web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 main:app
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
