services:
  - name: offspring-backend
    type: web
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:5000 backend.main:app  # Change -w 4 to -w 1
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
